FROM node:lts-hydrogen

WORKDIR /apps

COPY . .

RUN npm install --production

ENV MONGO_STRING=mongodb+srv://proroihan:pCpM7tfJrfcmZtma@roihan.wuzucp7.mongodb.net/test
ENV NODE_ENV=production
ENV PORT=4001


EXPOSE 4001

CMD ["node", "app.js"]