version: "3.9"
services:
  app:
    build: ./services/app/
    ports:
      - "4002:4002"
  users:
    build: ./services/users/
    ports:
      - "4001:4001"
  orchestrator:
    build: ./orchestrator/
    ports:
      - "80:4000"